languages: ['es', 'en']

title: Fernando Pérez Gutiérrez
email: fernaperg@gmail.com

assets:
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}
  source_maps: false
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn

exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - yarn.lock

ga_analytics: # Add Google Analytics tracking code

plugins:
  - jekyll-assets
  - jekyll-sitemap
  - jekyll-multiple-languages-plugin

name: presentation_kickster

permalink: pretty

url: # Add your site url
port: 8080
